server:
   port: 80

myProperties:
  flag: test

java:
  rmi:
    server:
      hostname: 192.168.31.214

com:
  sun:
    management:
      jmxremote:
        port: 1099
        authenticate: false
        ssl: false