spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

server: 
   port: 8080

management: 
  port: 8081
  health:
    mail:
      enabled: false
  security:
    enabled: false

params:
  count: countSql
endpoints:
  health:
    sensitive: false

test: faskdlfjklasjfklajsfkldfj