#设置自定义属性，用于别的地方的占位符
mycofig:
  database: spring_boot

spring:
  thymeleaf:
    cache: false
  aop:
    proxy-target-class : true # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
  profiles:
    active: dev



params:
  count: countSql
endpoints:
  health:
    sensitive: false

my-properties:
  flag: all

eureka:
  client:
    enabled: false
